### ISSUE TITLE
image order

### ISSUE THREAD

**Issue by joy211** [adam198824/cordova-plugin-image-picker#1]
now i can use the cordova-plugin-image-picker successfully, one problem is i can't display the image accroding the choose order, what can i do ?

**Comment by adam198824** [comment]
Sorry, this plugin is the old version, just for their own can use the language pack, you may find the wrong, go here to explain your problem here
https://github.com/wymsee/cordova-imagePicker

**Comment by joy211** [comment]
thank you, i found someone have same problem

**Comment by joy211** [comment]
thank i have solve my problem
